// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsLBox4yy2ENvdBoFP5_LVRGemB6oa_e4',
    appId: '1:767370574312:web:f122f341b40c94eec04c5d',
    messagingSenderId: '767370574312',
    projectId: 'chatapp-e50c0',
    authDomain: 'chatapp-e50c0.firebaseapp.com',
    storageBucket: 'chatapp-e50c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA77vVuFEg56ur7YxUwatQNmWTGGccb_Wo',
    appId: '1:767370574312:android:85b5ae7c606417a2c04c5d',
    messagingSenderId: '767370574312',
    projectId: 'chatapp-e50c0',
    storageBucket: 'chatapp-e50c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByCaQ4tjLovqCQJSEoI5wjV53txRb3DhM',
    appId: '1:767370574312:ios:fceb7f50b8586153c04c5d',
    messagingSenderId: '767370574312',
    projectId: 'chatapp-e50c0',
    storageBucket: 'chatapp-e50c0.appspot.com',
    iosBundleId: 'com.example.chatappfirebase',
  );
}
